# Content for the responsive case-study site. Every number is the verified figure from
# .claude/future_plans/2026-09-03_builder_case_study_v2.md and the deck-2 copy doc (3 Sep 2026).
DATE = "3 September 2026"
NAME = "Lukasz Rodzen"
ROLE = "architect · release owner · operator"
CONTACT = "[ADD LINKEDIN / EMAIL]"
CONTACT_HTML = "[ADD LINKEDIN / EMAIL]"  # becomes <a href=mailto:..> and a profile link once supplied
LOCATION = "Poland · remote"
OPMODEL = ("I own the architecture, the acceptance criteria, the controls, the release decision and production verification. "
           "AI models generate the implementation; I am accountable for the result.")
BOUNDARY = ("And I will tell you where the boundary is: the changes I would not make this way, "
            "and who I would bring in instead.")

LANDING = dict(
    kicker="Architect · AI delivery owner · Poland, remote",
    h1="One person built a live trading system, then the workflow that ships it.",
    lead=("I designed and operate an automated trading system that runs on Solana with my own funds, and the AI delivery workflow that ships every change to it. "
          "Two case studies: one for product and engineering readers, one for anyone hiring AI-native builders."),
    boundary="Personal engineering project. It trades only my own funds: no client assets, no investment service, no advice.",
    stats=[("16", "months, one architect"), ("1,300", "confirmed trades, my own funds"), ("1.3 s", "median trade execution"), ("134", "documented delivery runs")],
    fn="2,843 on-chain signatures behind the trades, verifiable on any explorer. 1.3 s is the median across all 1,303 timed trades; 927 ms on the enhanced path (n=117). Runs from 26 March to 1 September 2026. Measured " + DATE + ".",
    cards=[
        dict(n="01", title="The system", who="for product and engineering readers", href="the-system.html", accent="cyan",
             text=("A production system that turns public market signals into capped, auditable trades in about 1.3 seconds, with my own funds only. "
                   "Two servers, a custom Rust engine, and on-chain limits a trading key cannot bypass."),
             nums=[("1.3 s", "median from signal to landed trade"), ("2,843", "on-chain signatures, verifiable")]),
        dict(n="02", title="How I ship", who="for anyone hiring AI-native builders", href="how-i-ship.html", accent="green",
             text=("Six stages. Five model reviews on every plan, up to seven on every code change, then a separately run review. Fail-closed gates. "
                   "A memory loop that turns failures into rules: 134 runs, 235 recorded gaps, and the controls they produced."),
             nums=[("134", "documented runs"), ("235", "recorded gaps, 87 now rules")]),
    ],
)

# ---------------------------------------------------------------- case study 1
S1 = dict(
    slug="the-system", num="01", title="The system", tab="The system",
    subtitle="A live Solana trading system, specified, hardened and run by one person.",
    sections=[
    dict(id="cover", kind="cover",
         kicker="Case study 1 of 2 · the system",
         h1="One person. Two servers. A live trading system with my own money on-chain.",
         lead=("SKYNET turns Telegram calls and tracked wallets into ranked strategies and executes them on Solana "
               "in about 1.3 seconds, from a Rust engine I specified, had built, tested and hardened."),
         metrics=[("16", "months, one architect"), ("1,300", "confirmed trades, my own funds"), ("1.3 s", "median trade execution")],
         fn="2,843 on-chain signatures behind the 1,300 trades: 1,685 buys, 1,158 sells. 1.3 s is the median across all 1,303 timed trades (1,300 of them confirmed round trips); 927 ms on the enhanced path (n=117). Measured " + DATE + ".",
         first="journey", other=("Case study 2 · How I ship", "how-i-ship.html"),
         shot="health.webp", shot_caption="Operator home · live services, host vitals and database"),
    dict(id="journey", kind="journey",
         kicker="How it was built",
         h1="From a Grok chat window to a two-server operation in sixteen months",
         lead="Commits per month from git across the three repositories. 821 lines of code in April 2025; 368,000 by September 2026.",
         milestones=[
            ("Apr 2025", "One 1,295-line Python file, written in a Grok web chat. I had never opened an IDE."),
            ("Jul 2025", "Dashboard. Continuous tracking begins."),
            ("Oct 2025", "Claude Code becomes the workshop. Sharded price feed. First independent AI auditors."),
            ("Nov 2025", "Second server, Rust engine, encrypted tunnel. The delivery workflow is born."),
            ("Feb 2026", "Specialist sub-agents: research, plan, implement, audit, verify."),
            ("Mar 2026", "First confirmed on-chain trade."),
            ("Jun 2026", "On-chain program live on mainnet."),
            ("Sep 2026", "Three codebases, 134 documented workflow runs, my own funds in production."),
         ],
         note="The delivery loop is its own case study. This one is about what it produced."),
    dict(id="what", kind="four",
         kicker="What it does",
         h1="From a chat message to an on-chain trade, unattended",
         cards=[
            ("Listen", "149", "sources watched: 63 groups, 86 wallets, 4 chains", "Every message and every wallet transaction, around the clock."),
            ("Rank", "17", "exit strategies replayed per source, per regime", "Every source scored by what each strategy would have done."),
            ("Execute", "1.3 s", "median, all 1,303 timed trades", "A Rust engine on its own server builds the transaction itself and manages the exit."),
            ("Contain", "4", "fail-closed control layers", "Kill switch, per-trade and daily caps, circuit breakers."),
         ],
         note="I choose which public signals to follow with my own funds. Execution stays inside fixed caps, and every step is observable on one dashboard."),
    dict(id="infra", kind="infra",
         kicker="Infrastructure",
         h1="Two Hetzner servers, one encrypted tunnel, and the Solana blockchain",
         feeds=[("Telegram", "63 groups, read as messages arrive"),
                ("Birdeye price WebSocket", "15-second candles · 8 sharded connections"),
                ("Helius wallet WebSocket", "every transaction of 86 tracked wallets"),
                ("Market data", "Nansen · DefiLlama · CoinGecko · CoinMarketCap")],
         brain=("Finland · the brain · Python", ["Detection and queues · 8 workers, 5-layer dedup", "TimescaleDB · 28 GB · 12M rows",
                "Replay and sizing engine · nightly, 17 strategies", "Regime classifier · 27 signals, daily",
                "Dashboard · 202 endpoints", "Role-isolated views · fail-closed scoping"]),
         hands=("Nuremberg · the hands · Rust", ["Signal subscriber · verify, dedupe, fan out", "Jupiter routing · hand-built transactions",
                "Helius Sender · ~1 s to confirmation", "Position monitor · prices decoded on-chain",
                "Two lanes · main wallet · program-owned account", "Controls · kill switch, caps, breakers"]),
         chain=("Solana mainnet", ["Anchor program · on-chain limits on the trading key", "Jupiter v6 · live since Jun 2026"]),
         note=("Why two servers? Analysis is heavy and chatty. Execution has to be fast and quiet. Splitting them keeps a "
               "dashboard spike or a nightly job off the trade's critical path, and the engine keeps closing positions if the brain goes down.")),
    dict(id="engine", kind="points",
         kicker="The execution engine · built, not bought",
         h1="No trading library. The engine assembles the transaction itself.",
         lead="22 modules and 54,000 lines of Rust on their own server, doing one job: turn a verified signal into a landed Solana transaction and manage the exit.",
         points=[
            "Exactly one compute-unit limit and one price, Jupiter's instructions verbatim, a validator tip from a 10-account pool, address lookup tables. Preflight off, zero retries, confirmation polled every 200 ms against a ~400 ms block.",
            "Solana gives a transaction 1,232 bytes, and a fresh pump.fun route does not fit. Seven constant venue accounts are pre-warmed into the engine's own lookup table, appended and never prepended, because prepending re-inflates every healthy route.",
            "Exit prices are decoded from the pool's own bytes on-chain, 8 venues at exact byte offsets, with the router only as fallback. Signals cross the tunnel HMAC-signed with a freshness window and an idempotency cache, so a duplicate message is designed never to become a duplicate buy.",
         ],
         visual="stages",
         metrics=[("1,245", "test functions in the engine"), ("8", "pool layouts decoded on-chain"), ("≤10", "slots landing target")],
         fn="Every control fails closed: kill switch on entries, a 30 SOL cap enforced in three independent places, sizing that refuses on a missing SOL/USD price, a sell circuit breaker at three retries. 32K lines of tests."),
    dict(id="data", kind="points",
         kicker="Real-time data",
         h1="The price provider caps a connection at 100 addresses. I needed 552.",
         points=[
            "The feed is sharded across auto-scaling WebSocket connections, placed by SHA-256 hash so placement survives restarts. Python's built-in hash is salted per process and was rejected.",
            "The scaler acts on the busiest shard, not the average, with hysteresis and a dry run before any scale-down. An average of 77 can hide a shard at 85.",
            "Every 15-second candle lands in TimescaleDB. The hot read runs 230× faster through a continuous aggregate.",
         ],
         shot="shards.webp", shot_caption="Operator home · WebSocket shards per chain, live",
         metrics=[("8", "shards live"), ("552", "contracts on the feed"), ("12M", "candle rows in TimescaleDB")],
         note="Still open, and written down: the feed is certified for today's load, not for 1,500 contracts. The docs say so, and they list the defects that block the next step."),
    dict(id="controls", kind="controls",
         kicker="On-chain controls",
         h1="A trading key that cannot move the money",
         points=[
            "The funds sit in a program-owned account on Solana. The owner's wallet key is the only authority that can deposit, withdraw, pause, or revoke the trader.",
            "The engine holds a separate executor key that can only open and close positions, inside limits the program enforces on every transaction.",
            "Router instructions arrive as opaque account lists, so they are constrained rather than trusted: capped at 64 accounts, every writable account allowlisted, only two route discriminators accepted.",
         ],
         keys=[("Owner key", ["Deposit", "Withdraw", "Pause", "Revoke the executor"], "green"),
               ("Executor key", ["Open positions", "Close positions"], "cyan")],
         forbidden="cannot withdraw · ever",
         rules=["0.5 SOL per trade", "2 SOL per day", "lamports spent and tokens sold counted separately",
                "10 Token-2022 extensions rejected", "transfer fee capped at 200 bps", "the account pays its own fees from a separate counter"],
         metrics=[("14", "program instructions"), ("43", "error codes"), ("119", "tests, 46 unit + 73 mainnet-fork")]),
    dict(id="intelligence", kind="points",
         kicker="Intelligence",
         h1="Every tracked source replayed through 17 strategies, nightly",
         points=[
            "300+ sources × 17 exit strategies × 5 chains × 4 market regimes, precomputed nightly so every page loads instantly.",
            "Any result can be re-rendered at operator-defined position sizes, seven market-cap tiers deep.",
            "The market-regime label is validated on 21,345 real outcomes (z = 4.07, p < 0.0001). Caveat kept: 183 of 407 labeled days are backfilled with a simpler classifier, so this validates the labeling concept, not retroactive production accuracy.",
         ],
         visual="cube",
         metrics=[("17", "exit strategies"), ("6.2M", "precomputed rows"), ("27", "regime signals")],
         fn="The replay table carries five chain values; today's 40,908 tracked contracts sit on four of them. 17,820 tasks a night, about 25 minutes."),
    dict(id="failures", kind="beforeafter",
         kicker="Failures → controls",
         h1="The controls that exist because something broke",
         items=[
            ("A guard that was too eager deleted 28 real wallet trades across four instruction shapes.",
             "A 7,150-cell differential corpus that asserts every improvement is consumed, run before any parser change ships.",
             "7,150", "cells checked before a parser change"),
            ("A concentrated pool was priced 3.02× wrong by reserve ratio, producing a phantom stop-loss.",
             "A structural gate before any decoded price is trusted: decimals match, legs move opposite, both non-zero, then drift bands.",
             "3.02×", "the error the gate now refuses"),
            ("The nightly sizing job froze the web process 24 ms per spawn: uvloop's fork against a 3.3 GB address space.",
             "The worker moved out of process, 2,623 s → 329 s, and refuses to boot on uvloop at all.",
             "7.97×", "faster, and a boot-time assertion"),
         ],
         note="These three failures are retained as regression gates. Each now fails a build before it can reach production."),
    dict(id="measured", kind="tiles",
         kicker="Measured on the production system · " + DATE,
         h1="Measured, with the populations printed",
         tiles=[
            ("1,300", "confirmed trades", "2,843 on-chain signatures, verifiable on any explorer: 1,685 buys, 1,158 sells."),
            ("1.3 s", "median · all 1,303 timed trades", "927 ms on the enhanced path (n=117). 1,303 trades carry stage timings; 1,300 are confirmed round trips."),
            ("40,908", "contracts tracked · 4 chains", "SOL 34,215 · BSC 3,060 · ETH 2,870 · Base 763"),
            ("12.3M", "rows in TimescaleDB", "28 GB · 95 tables"),
            ("1,245", "engine test functions", "32K lines of tests"),
            ("119", "on-chain program tests", "46 unit + 73 mainnet-fork"),
         ],
         note="371K implementation lines and 5,066 commits across three repositories were generated under the delivery workflow. They measure the workflow's output, not me."),
    dict(id="close", kind="close",
         kicker="See it running",
         h1="Slides are claims. The system is proof.",
         lead="Two live sessions, no preparation on my side. Bring your own questions.",
         sessions=[("The product, live", "Any page of the running system, including areas I have not prepared: the feed, the engine, the on-chain controls, and the data behind every number here."),
                   ("The workflow, live", "A real task taken through the delivery loop while you watch: research, plan, AI implementation, separate review lanes, my go / no-go, verification in production.")],
         next=("Case study 2 · How I ship", "how-i-ship.html")),
    ],
)

# ---------------------------------------------------------------- case study 2
GROWTH = [("2025-11-26", 284), ("2025-12", 1920), ("2026-01", 4679), ("2026-02", 5386), ("2026-04", 5779),
          ("2026-05", 9300), ("2026-06", 10320), ("2026-07", 10700), ("2026-09", 11009)]
GROWTH_FLAGS = [("2025-11-26", "born, 284 lines"), ("2026-02-22", "sub-agents"), ("2026-03-27", "skills, Codex lanes, progress reviews"),
                ("2026-05-05", "the workflow audits itself"), ("2026-07-12", "dynamic model routing"), ("2026-09-03", "run 134")]

S2 = dict(
    slug="how-i-ship", num="02", title="How I ship", tab="How I ship",
    subtitle="The delivery workflow that ships SKYNET: AI models build every change, nothing ships until I approve it.",
    sections=[
    dict(id="cover", kind="cover",
         kicker="Case study 2 of 2 · how I ship",
         h1="AI models build every change. Nothing ships until I approve it.",
         lead=("One typed sentence becomes research, a plan, an implementation, five model reviews on the plan and up to seven on the code, a separately run review, "
               "a gated deployment and a written record. 134 documented runs. Every recorded failure kept."),
         metrics=[("134", "documented runs"), ("235", "recorded gaps"), ("121", "runs with a written scorecard")],
         fn="Runs from 26 March to 1 September 2026. 87 of the 235 gaps are written into a step, gate, script or test; 36 remain open. Measured " + DATE + ".",
         first="why", other=("Case study 1 · The system", "the-system.html"),
         runs=[("134", "1 Sep 2026", "Named sizing presets per tracked wallet", "3 days · 26 review findings, all validated at source"),
               ("133", "19 Aug 2026", "One-window wallet view, replay and live split", "shipped"),
               ("132", "17 Aug 2026", "Wallet ledger accuracy", "verified in production"),
               ("131", "14 Aug 2026", "Heavy computation moved out of the web server", "2,623 s → 329 s"),
               ("130", "13 Aug 2026", "Sizing freshness guarantees", "10 fix rounds · 31/31 findings confirmed"),
               ("129", "9 Aug 2026", "Position-sizing engine certified", "in production")],
         runs_caption="Recent change history · latest six runs of 134 · every run leaves a plan, review decisions, fix rounds, test records, a deployment record and a retrospective"),
    dict(id="why", kind="growth",
         kicker="Why it exists",
         h1="It grew because runs failed",
         lead=("April 2025: code pasted from a Grok chat. October 2025: the first independent AI auditor. 26 November 2025: the workflow file is born "
               "at 284 lines. Today it is 11,009 lines across 93 commits, and each addition is dated to the run that needed it."),
         note=("Each major rule links back to the failure that required it. Gates carry the run that needed them: "
               "“added 2026-07-03, Run 108”, “operator-caught 2026-08-18”. Around it grew a system: 26 reviewer and builder roles, "
               "22 reference skills, 3 testing harnesses, and 1,000 commits to the workflow folder alone.")),
    dict(id="loop", kind="loop",
         kicker="The loop",
         h1="Six stages. I own scope, release and verification.",
         stages=[
            ("Understand", "The request and the real system: architecture first, then production health, before a single query.", False, "Architecture-understanding block, production health snapshot"),
            ("Route", "By complexity. Money, schema or security forces the deep route and cannot be downgraded.", True, "Complexity score and the route decision, logged by name"),
            ("Research and plan", "An AI planner writes the plan; every database table, column and file it names is checked to exist.", False, "The plan, with every named table, column and file checked to exist"),
            ("Implement", "AI models write the code. The recorded changes prove each claimed edit actually happened.", True, "Recorded code changes per claimed edit; database-structure and code-quality checks"),
            ("Review", "Five model reviews on the plan, up to seven on the code, then a separately run review by a different vendor's model.", False, "Five written review decisions per phase; the separate review's decision and receipts"),
            ("Decide and verify", "I approve the release, monitor production for ten minutes, then run the documented smoke test myself. Automated checks gate the deploy.", True, "Deploy receipt, ten-minute monitor log, my sign-off"),
         ],
         routes=[("Simple", "about 15 minutes"), ("Moderate", "60 to 90 minutes"), ("Complex", "2 to 3 hours, up to days with fix rounds")],
         note="Eight checkpoints support those three decisions. Every override is logged by name; the two that touch security or isolation are refused outright."),
    dict(id="failures", kind="beforeafter",
         kicker="Failures → controls",
         h1="Six times something broke, and what exists because of it",
         items=[
            ("The AI reported “done”. The file was unchanged.", "Every claimed edit is proven by the recorded changes before any reviewer sees it.", "Run 31", "Apr 2026"),
            ("An agent declared a test tool “not installed” after one shell lookup. It was installed.", "A standing rule: never assert a tool is missing from one lookup; the check looks in every valid install location.", "4 Jun", "2026"),
            ("A handover said the tests passed. The test record showed three failures, on transaction-critical code.", "Pass or fail is derived by a script from the test record, never from prose.", "Run 108", "Jul 2026"),
            ("Twelve external rounds said yes. The deploy locked the whole dashboard out for an hour: a refusal shipped before its data existed.", "A deploy-sequencing gate: populate before you enforce. Plans carry a release condition per feature.", "Run 127", "Aug 2026"),
            ("The safety test was green because its inputs were chosen where old and new code agree.", "Widened to 25 cases it went red: 28 production cases would have been handled wrongly. That corpus is now a gate.", "Run 132", "Aug 2026"),
            ("Eleven review rounds read the code; nobody opened the page. The feature would have refused every request.", "One live round trip through the real screen before reviewers are dispatched. Caught before release by the first test that did.", "Run 134", "Sep 2026"),
         ],
         note="From the run tracker, verbatim: “Every single one was found by widening the check, never by re-reading the same layer harder.”"),
    dict(id="reviewers", kind="reviewers",
         kicker="Who reviews",
         h1="Five reviews on the plan, seven on the code, then one run separately",
         points=[
            "Different models, different review roles, run in parallel: two Claude Opus reviewers, one OpenAI Codex, one xAI Grok, and the coordinating model's own verdict. Each is told: you are the auditor, not a rubber stamp.",
            "Some reviewers cannot see the others' findings. The data-flow tracer works from the plan and the code alone. A validator removes any line number or value that does not exist in the real code.",
            "The separate round runs outside the workflow. A brief is built from pinned code versions, 12 patterns of secrets are removed, a 28-check gate refuses a dirty brief, and I paste it into a separate OpenAI Codex session myself. No timeout auto-proceeds.",
         ],
         lanes=[("Plan review · 5 lanes", ["Opus plan auditor", "Opus architecture reviewer", "OpenAI Codex", "xAI Grok", "Orchestrator verdict"]),
                ("Code review · 5 lanes + 2", ["Opus code auditor", "Opus architecture reviewer", "OpenAI Codex", "xAI Grok", "Orchestrator verdict", "Data-flow tracer · blind to other findings", "Validator · removes invented references"]),
                ("Separate round · a different vendor's model", ["Four specialist reviews plus a synthesis: bugs, architecture, verification, security", "A block sends the work back to plan revision", "A finding cannot be dismissed without a receipt"])],
         metrics=[("5", "model reviews on every plan"), ("7", "reviews on every code change"), ("28", "checks before a brief leaves")],
         fn="Multiple AI reviewers are not an independent security audit. Where money or security is at stake, the boundary is a human specialist."),
    dict(id="knowledge", kind="knowledge",
         kicker="What the reviewers are given",
         h1="Official references first, and proof they were used",
         columns=[("22 reference skills", "Vendor documentation, packaged", ["Solana program safety", "Anchor testing", "Jupiter integration", "Helius streaming", "Raydium · Orca · Meteora · pump.fun", "Token-2022 rules", "Security checklists", "Postgres patterns"]),
                  ("Live documentation servers", "Read before any integration decision", ["Solana Foundation docs", "Helius docs", "Jupiter docs", "Nansen data", "Vendor GitHub sources"]),
                  ("3 testing harnesses · 4,763 lines", "Known failure patterns, one per past incident", ["Data validation · 14 patterns, 14 satisfied", "On-chain program · 43 patterns", "Execution engine · 46 patterns, 28 enforced", "Grows after every run"])],
         points=[
            "Citing a reference is not applying it. A seven-checkpoint chain follows each skill from the plan, through the implementation, to the reviewer's compliance table, with file and line citations at each step.",
            "A review that does not cite the harness patterns it consulted is rejected and re-run. The pattern list is read automatically; nobody hand-counts it.",
            "Community snippets are treated as untrusted. One shipped the wrong byte offsets for a trading venue; official sources are now a hard gate.",
         ],
         metrics=[("7", "checkpoints on skill use, per run"), ("14/14", "data patterns satisfied on the last run")]),
    dict(id="scorecards", kind="scorecards",
         kicker="Scorecards",
         h1="Every run is graded, and so is every reviewer",
         card_caption="One real scorecard · run 133 · 19 Aug 2026 · from the written progress review",
         rows=[("Coordinator gates", 11, 12, "one recorded as not run, never as passed"), ("Reviewer checks", 10, 10, ""),
               ("Security, UI, verification", 8, 8, ""), ("Harness patterns cited", 14, 14, "plus 3 new patterns added"),
               ("Skill-use chain", 7, 7, "citations at every step"), ("OpenAI Codex lane", 10, 10, "no degraded rounds"),
               ("xAI Grok lane", 8, 10, "unique catch the other two missed; text output, not structured")],
         lineages=[("Claude Opus", "plans, implements, reviews architecture and code; max effort on complex runs"),
                   ("Claude Sonnet", "validates plans and findings against the real code and data"),
                   ("OpenAI Codex", "internal review lanes and the separately run review"),
                   ("xAI Grok", "independent bug hunter, added July 2026 after the Gemini lane was retired"),
                   ("Data-flow tracer", "checks the promised data path at plan time and again in the code; 30 passes recorded, up to 35 of 35 assertions")],
         note="A “no” is a gap by definition. It gets an ID, a severity and a suggested fix, and the next run is checked for it.",
         metrics=[("121", "runs with a written scorecard"), ("5", "lineages graded per run"), ("30", "data-flow passes · up to 35/35")]),
    dict(id="gates", kind="gates",
         kicker="Where it stops",
         h1="A claim without evidence stops the run",
         gates=[("“I edited the file.”", "The recorded changes show nothing changed. The claim is false. Back to implementation."),
                ("“The plan uses this piece of data.”", "That data does not exist in the database. Blocked before a line is written."),
                ("Transaction-critical code, no record that the tests ran.", "No deploy. The test record must exist and match this run."),
                ("The external brief contains a server address.", "Hard block. The brief never leaves the machine."),
                ("Fewer than four of five reviewers finished.", "Deployment blocked. A thinner panel is not a panel."),
                ("The external verdict is not back yet.", "Wait. There is no timeout. The point of the gate is the independent opinion.")],
         metrics=[("34", "catalogued gates"), ("144", "“hard block” markers in the workflow file")],
         note="Each gate is traceable to the run that needed it. The rule inside the file, verbatim: “Zero insertions or deletions means the implementer's claim is false.”"),
    dict(id="memory", kind="memory",
         kicker="Memory",
         h1="Whatever breaks once becomes a rule the next time",
         chain=[("Run", "a task goes through the loop"), ("Handover", "a save-file that survives the AI losing its memory mid-run"),
                ("Review", "the transcript is scored against a rubric, with quoted evidence"), ("Gap", "anything that should have fired and did not gets an ID and a severity"),
                ("Rule", "the fix is written into the workflow; a text check confirms it was added, later runs test whether it works"),
                ("Archive", "plan, code changes, review decisions and file fingerprints are frozen; the architecture document is rewritten from the code")],
         gap_caption="The life of one gap · G-127a · run 127 · 4 Aug 2026",
         gap=[("found", "a refusal shipped before its data existed; the whole dashboard locked out for an hour"),
              ("recorded", "G-127a, severity HIGH, suggested fix, in the run tracker"),
              ("designed", "a deploy-sequencing gate: populate before you enforce"),
              ("proven", "a text check shows the gate in the workflow file; the next run fires it"),
              ("retired", "removed from the open list after three confirming runs")],
         metrics=[("196", "run archives since Dec 2025"), ("252", "archived handovers"), ("235", "recorded gaps, 36 still open")],
         fn="196 archives since December 2025. The run tracker with its scorecards starts on 26 March 2026, which is why it counts 134 runs.",
         note="From the handover rules, verbatim: “The handover is a hypothesis about state. Verification commands are proof.” Automated checks execute the tests; model reviewers interpret the evidence; I own the release decision."),
    dict(id="measured", kind="tiles",
         kicker="Measured · " + DATE,
         h1="Measured, with the populations printed",
         tiles=[
            ("134", "documented runs · 112 with a full retrospective", "26 March to 1 September 2026. Analytics 70 · execution engine 17 · on-chain program 7 · cross-repo 9. Fifty declared complex."),
            ("235", "gaps recorded · 87 written into a step, gate, script or test", "36 still open today. A gap leaves the open list only after three confirming runs."),
            ("121", "runs scored by a written progress review", "Each scores gates fired, reviewer checks, skills used, harness patterns cited."),
            ("45", "runs where the separate review found something all internal reviews missed", "Of 52 runs that record the field; 7 record that it did not."),
            ("30", "data-flow verifications recorded as passed", "Up to 35 of 35 assertions."),
            ("−84.8%", "tokens on deep reviews after routing", "Zero missed HIGH or CRITICAL findings across three A/B samples; −57.5% on standard runs. Transaction-critical work never routes cheaper."),
         ],
         note=("58 of 112 runs recorded zero post-deploy bugs; the others are documented too, including one severity-one incident and one shipped-with-reverts. "
               "Multiple AI reviewers are not an independent security audit; where money or security is at stake the boundary is a human specialist.")),
    dict(id="close", kind="close",
         kicker="See it running",
         h1="Slides are claims. The archive and the system are the evidence.",
         lead="In an interview I can walk through one archived change and one live product flow: the evidence, the release decision, the result, and the limits of this approach.",
         sessions=[("One archived change, end to end", "A real run from the archive: the request, the plan, the review decisions and fix rounds, the separate review's verdict, my release decision, and what production showed afterwards."),
                   ("One live product flow", "The system this loop built, running: a signal arriving, the engine executing, the record it leaves, and the numbers behind case study 1.")],
         team="In a team I would own: scope and acceptance criteria, the review gates, release decisions, and the retrospective loop. Engineers own the code; the workflow makes their review load smaller, not larger.",
         next=("Case study 1 · The system", "the-system.html")),
    ],
)
