# The run, step by step. Source: audit3/workflow_breakdown.md §2 (step numbers and quotes are the runbook's own).
O, S, X, G, ME = "Claude Sonnet", "script", "OpenAI Codex", "xAI Grok", "Me"
OP = "Claude Opus"

def st(id, title, sub, what, who, reads=None, leaves=None, block=None, mine=None):
    d = dict(id=id, title=title, sub=sub, what=what, who=who)
    if reads: d["reads"] = reads
    if leaves: d["leaves"] = leaves
    if block: d["block"] = block
    if mine: d["mine"] = mine
    return d

RUN = dict(id="run", kind="steps",
    kicker="The run, step by step",
    h1="One typed sentence in. A gated, recorded release out.",
    lead=("The six stages on the cover unfold into ten phases plus a final one, below, in the order the runbook's own to-do list executes them for a complex change. "
          "Open a phase, then a step, to see who acts, what they must read first, what evidence they leave, and what stops the run. Step numbers are the runbook's own."),
    phases=[
        dict(num="Phase 0", title="Pre-flight", who="Scripts and the coordinator, before the request is even read", steps=[
            st("0.A", "Are the reference books intact?", "A broken skill link silently degrades every reviewer downstream", 
               "A script checks that every skill package, stored as a link, resolves. The runbook's reason: a stale brief is recoverable, but a quietly broken skill bundle invalidates the audit itself. Added after a 47-day silent degradation nobody noticed.",
               [S], block="A skill link is broken"),
            st("0.B", "Refresh the official Solana playbook", "Only for blockchain tasks, and deliberately non-blocking",
               "The coordinator pulls the latest official Solana development skill from the Solana Foundation's public repository. Network failure or a partial download warns and continues.",
               [O], leaves="A refresh trace file for the run"),
            st("0", "Is there a half-finished run in the building?", "Leftover state from another task must never be resumed by mistake",
               "The recovery files on disk are compared with the archive. Clean: proceed. Stale after an archive: pause and ask me. In flight: hard stop until I choose resume, archive or abandon. It exists because a research brief for task A was once used to audit the plan for task B.",
               [S, O], block="A previous run is still in flight"),
        ]),
        dict(num="Phase 1", title="Understand and route", who="The coordinating model · my decision at the end", steps=[
            st("1", "Read the request", "One sentence from me; a separate intake gate if it is a trading incident",
               "The task text is parsed. If it is bound to a trading incident, an intake gate fires first: the incident register must be read, and nothing may be marked fixed before a signed closure certificate exists.",
               [O]),
            st("1.5", "Which system is this?", "Seven buckets decide the harness, the skills and whether money gates apply",
               "The work is classified: analytics, trading engine, on-chain program, both Solana codebases, workflow hardening. This one label later decides which test harness fires, which expert skills are injected and whether the money-path gates apply. The current commit ID is pinned so a later gate can detect the code moving underneath the audit.",
               [O], leaves="The audit brief: the single source of truth every later command reads"),
            st("1.6", "Is there a screen involved?", "Dashboard scope and impact level",
               "UI scope is detected and given an impact level, which later decides whether a design agent is spawned and whether the browser is photographed before and after.",
               [O]),
            st("2", "Architecture first, through the navigation index", "Rule Zero: “Use the navigation system, don't just grep”",
               "The coordinator reads the navigation index, finds the matching entry, follows it into the 19,514-line architecture map, and then reads the actual source files it names. No production query is allowed yet.",
               [O], reads="Navigation index → architecture map section → source files"),
            st("2✓", "Checkpoint: prove you understood before you touch production", "A tick-box gate, all boxes or no progress",
               "An architecture-understanding block must be written, including what a healthy state looks like for this subsystem. “Do not proceed if any box is unchecked.” Navigation and server commands may not run in parallel.",
               [O], leaves="The architecture-understanding block", block="Any box unchecked"),
            st("3", "Health-check the live system", "Only now, because now the coordinator knows what healthy looks like",
               "Live processes, configuration flags, recent critical errors and a row count from the production database are read and saved as the system state for the run.",
               [O], leaves="The system-state snapshot"),
            st("3.0B", "Photograph the browser", "A baseline to diff against after deployment",
               "A headless browser captures a screenshot, the JavaScript error count and the list of API calls. The after-picture at the end of the run is compared with this.",
               [S], leaves="Browser baseline: screenshot, error count, API inventory"),
            st("4", "Present the route and wait", "Simple, moderate or complex, from risk rather than file count",
               "The complexity assessment and recommended route are shown in plain and technical language, then the run stops. If the task auto-escalated for security reasons, such as keys, wallets or fund movement, the downgrade option is withheld: the complex route is mandatory.",
               [ME], mine="Proceed, upgrade, downgrade or cancel. Every override is logged by name."),
            st("4.5", "Pick the external bug-hunter's depth", "Light, single, or manager mode where it spawns its own sub-hunters",
               "The depth of the OpenAI Codex lane is set from complexity. Ten listed conditions escalate a moderate run to manager mode anyway, among them any authentication, wallet or money-movement logic.",
               [O]),
        ]),
        dict(num="Phase 2", title="Research", who="A researcher agent gathers · a validator fact-checks · the coordinator validates", steps=[
            st("5.1", "Refresh the audit context", "Live schema and recent errors, re-exported if older than a week",
               "A script re-exports the production database schema and the recent error log so that planning happens against today's reality.",
               [S], leaves="Fresh schema export and error digest"),
            st("5.2", "Delegated research, validated upward", "“Subordinates research, boss validates”, never the other way round",
               "A researcher agent maps affected files, callers, consumers, data sources and user-facing paths, reading vendor documentation from the vendors' own live documentation servers first. The coordinator validates every finding against local knowledge and records what was accepted and what was rejected. Mandatory for every moderate and complex task.",
               [OP, O], reads="Navigation, architecture map, code, live vendor docs", leaves="The research brief, to a fixed template"),
            st("3.1", "Do the research files actually exist?", "An empty brief stops the run",
               "A hard gate: if the research brief is missing or empty, stop.", [S], block="The research brief is empty"),
            st("3.15", "Fact-check the research", "Every function, line, data source and column, against the real files",
               "A validator agent re-reads every claim in the brief against the code. A failure re-runs the researcher. The reason, in the runbook: a brief once said a function had 18 signals; reality was 9 stale ones; nobody verified; three hours and forty-five minutes and a full revert were lost.",
               [O], leaves="The validation report", block="A claim in the brief is false"),
            st("3.16", "Did we map the blast radius?", "For every change target: who calls it and who reads its output",
               "The brief must contain a feature impact map with explicit full or partial coverage flags, so a change cannot fan out into consumers nobody listed.",
               [O], block="No impact map"),
            st("SEP", "View separation gate", "Fires from a computed flag, not from an agent noticing a keyword",
               "A script decides whether the change touches the boundary between the operator's own view and any other account view. If it does, the brief must classify every changed path, and the canonical separation contract governs.",
               [S], block="The separation matrix is missing when the flag fires"),
            st("3.2", "Verify the data says what we think", "A real sample from production for every data source touched",
               "The coordinator queries production for an actual sample of every data source the task touches. Hard gate on mismatch. The incident: a dashboard showed three of five signals; reality was zero of thirteen; nobody had queried production before planning.",
               [O], block="The data does not match the assumption"),
            st("3.2.5", "Do we need a data-flow trace?", "Four automated triggers",
               "Complex work, a database migration, a new value written into a shared column, or a new background loop each require a data-flow trace at plan time. Written after run 37 shipped two catastrophic data-loss bugs that all four internal reviewers missed and only the external reviewer caught.",
               [S], leaves="The trace-required flag in the audit brief"),
        ]),
        dict(num="Phase 3", title="Plan and validate", who="A planner agent writes · the coordinator and scripts check · revision loop", steps=[
            st("3.3", "The plan", "Written by a different model than the coordinator, with its own re-read of the architecture",
               "A planner agent is told it is not executing the research brief blindly: it must independently re-read navigation, architecture and source. The plan includes tests, rollback, dependencies and a mandatory section naming the skills it used, with the file and lines actually opened.",
               [OP], reads="Navigation, architecture, code, the required skills", leaves="The plan, with its skills section"),
            st("3.5", "The researcher validates the planner", "Six checks, including a ground-truth cross-check of every table named",
               "Completeness, pattern adherence, scope, integration, skills, and whether every database table the plan names was actually verified by the research. The reason: run 42's plan named five tables that did not exist and three same-lineage reviewers approved it.",
               [O], leaves="Valid, minor fix in place, or a revision request"),
            st("3.5.4", "Mechanical existence gate", "A thirty-second grep that catches every phantom name before the panel spawns",
               "A script extracts every table, column, route, file path and environment variable in the plan's code blocks and checks each exists, with batched database queries and file tests. Deliberately not an AI. Complex runs only.",
               [S], block="Any phantom symbol"),
            st("3.5.5", "Integration verification", "Does the plan match the code that already exists?",
               "Existing patterns, SDK rules, cross-system contracts, database integration and explicit preservation of existing features are checked and scored.",
               [O], leaves="A scored integration document"),
            st("3.6", "Revision loop", "At most two automatic iterations, then I handle it",
               "Major issues go back to the planner with its memory intact. A reject verdict first sends the researcher back for missing ground truth. Audit-driven revision rounds later in the run are recorded by name; the deepest recorded is nine.",
               [OP, ME], mine="After two automatic iterations, the decision is mine"),
        ]),
        dict(num="Phase 4", title="Five-way plan audit", who="Three vendors in parallel · quorum three of four · then my approval", steps=[
            st("5", "Launch five reviewers in one message", "Nobody can read another's verdict, because none exists yet",
               "A plan auditor and an architecture reviewer (Claude, maximum effort on complex runs), an OpenAI Codex lane and an xAI Grok lane through their wrappers, the coordinator's own verdict, and a cross-validator when dependencies or documentation servers change. Grok is explicitly non-blocking while it earns its place.",
               [OP, X, G, O], reads="The plan, the harness patterns, the injected skills", leaves="Five written verdicts"),
            st("5.1", "Four mandatory preambles", "“If you have not read the actual source files, your review is invalid”",
               "Every reviewer is told: you are the auditor, not a rubber stamp; architecture first; read the actual source files; and on trading work, a blocking SDK-compliance check with live verification of every external API call.",
               [O]),
            st("5.2", "Quorum", "Three of four legacy lanes must return valid output",
               "No verdict until at least three of the four lanes have returned. A reviewer that omits the mandatory harness-patterns section is re-spawned once, then excluded from quorum; if quorum drops, the run blocks and asks me.",
               [O], block="Fewer than three valid lanes"),
            st("5.3", "Extract the data-flow trace", "Fail-closed: a missing or placeholder trace re-spawns the reviewer",
               "When a trace is required, the architecture reviewer's trace is extracted between explicit markers and checked: non-empty, exactly five sections, no placeholder text.",
               [S], leaves="The trace artifact the implementer must satisfy", block="The trace is missing or malformed"),
            st("5.4", "Check the checkers", "The coordinator reads the code behind every finding",
               "A mandatory to-do item: independently validate every plan-audit finding by reading the code and verifying the claim before acting on it.",
               [O], mine="Approve the plan for implementation, or send it back"),
        ]),
        dict(num="Phase 5", title="Implement", who="A separate agent writes the code · scripts prove every claim", steps=[
            st("P9", "Stamp the before-picture", "Once, and never re-stamped",
               "Each repository's commit ID is recorded before implementation. It is never re-stamped on a resume or a fix round, so the diff the external reviewer later sees is cumulative.",
               [S], leaves="Pre-implementation commit IDs"),
            st("6", "A separate implementer", "Never the coordinator, on moderate and complex work",
               "The coding agent's model and turn budget come from a tier matrix; blockchain work always gets the strongest tier. The implementer follows the plan exactly and adds nothing; if the code differs from the plan's assumptions it stops and the plan is revised rather than the scope silently expanded. It must return a skills-applied section naming the specific rule used per skill. If it runs out of turns it hands over to a continuation implementer, at most three deep.",
               [OP], reads="The approved plan, the research brief, the trace", leaves="The diff and the implementation report"),
            st("G-29", "Implementer output freshness", "Silent degradation converted into a loud one",
               "If the implementer's report is missing or older than the plan, which happens when the coordinator applies fix-round edits itself, either a fresh implementer is spawned or a sentinel with per-skill file-and-line citations is written. Neither: the scoring pass must mark the skills checkpoints as failed, not as unverified.",
               [S, O], block="Stale or missing implementer output without a sentinel"),
            st("6.1", "Post-implementation impact validation", "“Zero insertions or deletions means the implementer's claim is false”",
               "The recorded diff is checked for every file the implementer claims to have changed. The tenant-separation flag is re-affirmed from the real diff. The last three runs' recurring bugs are grepped for.",
               [S], block="A claimed edit shows no change"),
            st("6.2", "Skills gates", "Presence is not application",
               "A nine-check matrix maps task characteristics to skills that must appear. On blockchain work a stricter citation gate demands an actual rule number or pattern ID. This one is an advisory gate: after two retries it logs that it degraded and lets the run continue, so it is not counted among the gates that stop the run.",
               [O, S]),
            st("8.7", "Schema validation gate", "Every column in the SQL diff, against the live database",
               "The incident: a helper referenced a column that did not exist and 17 review rounds approved the code.", [S], block="A missing column"),
            st("8.8", "Static linter gate", "An unused variable the plan named is a wiring failure",
               "The incident: a value was loaded from the database and never wired to the page; 17 review rounds approved; the user saw blank rows.", [S], block="An unused plan-named variable"),
        ]),
        dict(num="Phase 6", title="Five-way code audit", who="Same panel, now against the real code · the coordinator verifies the verifiers", steps=[
            st("7", "The panel, against the code", "On blockchain runs the cross-validator goes first and can stop the audit",
               "A code auditor, the architecture reviewer, OpenAI Codex and xAI Grok in parallel; on traced runs a data-flow tracer joins, with fresh eyes: it does not read the plan-phase findings. Same quorum rule.",
               [OP, X, G, O], leaves="Five verdicts, the tracer's delta report", block="Fewer than three valid lanes"),
            st("7.1", "Functional testing requirement", "Pick an input, trace it through the code, compare to a known-good reference",
               "Reviewers must go beyond syntax: trace one concrete calculation step by step, test edge cases, and publish the results.",
               [OP, X, G]),
            st("CP7", "The coordinator verifies the verifiers", "Line numbers exist, values match the database, then its own trace",
               "Each reviewer's numeric trace is extracted; line numbers are checked to exist; values are checked against the live database; expected values must have a real source. Then the coordinator performs its own independent trace and cross-checks the reviewers against each other. Explicit anti-gaming measures; hard gates prevent a pass.",
               [O], block="A reviewer's trace does not hold up"),
            st("7.2", "Official sources override", "A vendor's documentation beats a reviewer's claim about that vendor",
               "Any external reviewer's claim about a provider's behaviour is checked against that provider's own documentation before it is accepted.", [O]),
            st("8.5", "Post-fix re-audit", "When a round had criticals and the fix touched a shared column",
               "The fix itself is re-audited, by a different lane than the one that found the problem.", [OP], block="Fires on the trigger; the fix must pass"),
            st("6.6L", "Skill application ledger", "One row per rule, not per skill, each mapped to code",
               "On blockchain runs the code and security reviewers must table every individual rule of the injected skills with a code location and a verdict. Any unmapped or violated row forbids approval. The incident: code shipped with an unchecked token freeze authority while the security report claimed to have applied the very skill section that forbids it.",
               [OP, S], block="Any rule unmapped or violated"),
        ]),
        dict(num="Phase 7", title="Pre-deploy gates", who="Scripts execute what reviewers only read", steps=[
            st("8.6", "Live-execution gate", "“Do not proceed on any timeout. All other paths are forbidden.”",
               "Write-and-time code is dry-run against the real database. New read helpers are run against a known canary entity. A zero-row mismatch or a missing canary on a complex run blocks.",
               [S], block="A dry run fails or the canary probe mismatches"),
            st("7B", "Runtime test execution", "Fund-moving code must have run, on a mainnet fork, in this run",
               "A test runner must produce a transcript keyed to the run. The gate then re-extracts the cited test bodies from disk, cross-checks pass counts against the framework's own totals, and hashes the raw log against the archive. Missing transcript, count drift, empty proofs or zero entry-point coverage all block. The comment trail shows this gate re-hardened a dozen times against ways a forged transcript could slip through.",
               [S], leaves="The signed test transcript", block="No transcript, count drift, or zero coverage"),
            st("7B.5", "Harness flip integrity", "Marking a pattern satisfied needs two mechanical citations",
               "A non-trivial assertion and proof of reachability with no early exit. The incident: four patterns were flipped to satisfied by editing a count; one cited test asserted that true is true, fourteen others exited before reaching the code they claimed to test.",
               [S], block="A bare claim of coverage"),
            st("10", "Security gate", "First: has the code moved since the audit began?",
               "If the repository has moved since the commit pinned at step 1.5, the findings may be stale and the run blocks. Then a recommendation: security-relevant work spawns a security auditor that itself spawns three sub-auditors, blinded to its own findings to prevent anchoring. I always have the final say.",
               [S, OP, ME], block="The code moved underneath the audit", mine="Spawn the security auditor, or accept the recommendation not to"),
        ]),
        dict(num="Phase 8", title="The external round", who="A different vendor's model, in a session I open myself", steps=[
            st("9A", "Trigger", "Mandatory on traced work, money-moving work, and complex UI work",
               "The origin: run 37's rollback bug would have wiped 22,102 production records and was caught only by the operator's external reviewer, while all four internal lanes approved. The money-path trigger became unconditional after 15 consecutive runs in which the external round caught what the internal panel missed.",
               [S], block="A required trace is missing: inferring “no file means not required” fails open"),
            st("9A.1", "Freeze, assemble, redact", "Nothing is reviewed dirty",
               "The in-scope state is committed and its commit ID recorded. The brief builder refuses to render from dirty files. It pulls plan, brief, trace, changed files, implementer output and navigation ranges, and replaces every server address, private network address, database identifier, key path and dashboard credential with redaction tokens before writing, stamping a receipt of how many replacements it made.",
               [S], leaves="The redacted brief and its receipt"),
            st("9A.1-B", "Render the prompt", "A universal template with two independence guards written in capitals",
               "Known anti-patterns must be framed as rebuttable, never “do not re-flag”. Per-lane targets are a floor, never a ceiling, with explicit latitude to look outside the changed files, because “the orchestrator is a single model and will miss things.”",
               [S]),
            st("9A.1-C", "Who runs it", "Default: I paste it into my own separate session",
               "The default channel preserves full process independence: I paste the brief into a separate OpenAI Codex session and paste the verdict back. A fallback where the coordinator spawns the external model itself is labelled reduced independence and can only be launched by a script that refuses to run without my verbatim authorising words, logged before spawning.",
               [ME, X], mine="Run the external session myself"),
            st("9A.1.5", "The prompt gate", "Twenty-eight checks; fail-closed if the checker itself is missing",
               "Any inline production access, unresolved template slot, wrong skill bundle for the system type, or empty navigation range blocks. If the checker script is missing, the run still blocks.",
               [S], block="Any of 28 checks, or the checker is absent"),
            st("9A.4", "Receive and validate the verdict", "Mechanical validation of every finding, and a downgrade guard",
               "Freshness of the brief's commit, format conformance, artefact shape, degraded-round detection, then each finding validated mechanically. On money-moving work, downgrading an external critical or high finding requires a code receipt and, where traced, a runtime receipt proving the neutralising path executes. A second external auditor agreeing with the downgrade does not satisfy the gate, because that has happened and production disproved it within a day.",
               [O, ME], block="A downgrade without receipts: the finding stays open", mine="Accept, refute with receipts, or send back to plan revision. There is no timeout."),
        ]),
        dict(num="Phase 9", title="Deploy and verify", who="Scripts stage exactly this run's files · machines test before I do", steps=[
            st("11", "Deploy", "Only from the default branch, only this run's files",
               "A reconcile gate runs once per deployed repository and blocks if a foreign or missing file appears. Then pull and restart on the servers by script, a release build for the Rust engine or an on-chain deploy for the program, and ten minutes of monitoring.",
               [S, ME], leaves="Deploy receipt and monitor log", block="A foreign or missing file in the staged set", mine="Ship, or do not ship"),
            st("9C-auto", "Automated browser verification", "Mandatory-fire: the trigger once met and zero browser calls happened",
               "The browser is driven for real; console errors and network calls are compared with the baseline from step 3.0B. Added after a run whose 3.7-megabyte transcript contained no browser tool call at all.",
               [S], leaves="The after-picture, diffed against the baseline", block="The precondition is met and the check did not fire"),
            st("9C-data", "Data validation harness", "The same numbers across pages and filters must agree",
               "For data-pipeline work, the harness cross-checks figures across pages and filter combinations. It evolves after every run.", [S], block="Cross-page disagreement"),
            st("9C", "The human checklist, with a twist", "“Did you test all these yourself?”",
               "Before I see anything, every checklist item is tagged as browser-verifiable or human-only, and the coordinator runs every automatable item itself. I get only what genuinely needs a human. Then a hard wait: the run does not advance until I report back.",
               [O, ME], mine="Confirm the result, or report defects and start another fix-and-review cycle"),
        ]),
        dict(num="Final", title="Document, archive, self-score", who="The coordinator rewrites the map · an archive agent freezes the evidence · the run grades itself", steps=[
            st("F1", "Session summary", "Everything the run did, with real commit hashes",
               "Artefacts, audit files, changed files, both five-way verdict sets, an executed-versus-read ledger, gate evidence, skills evidence, external-round evidence, post-deploy issues.",
               [O], leaves="The session record"),
            st("F1.5", "Rewrite the architecture map", "By the coordinator directly, never delegated",
               "A fresh agent succeeded at this one time in four across earlier runs, so the coordinator does it itself: read the changed source files, not the plan; rewrite the affected sections as current state; sync any canonical contract whose domain was touched; regenerate the navigation index from section markers; run the drift test; spot-check two or three documented flows against the code.",
               [O], reads="The changed source files", leaves="Updated architecture map and navigation index", block="Any of seven quality checks fails"),
            st("F1.99", "Was the summary actually written?", "A chokepoint added after five zero-byte session files",
               "A hard gate that the session record exists and has content, plus a pre-archive guard for blockchain artefacts.", [S], block="A zero-byte record"),
            st("F2", "Archive", "Plan, diff, verdicts, the raw transcript, file fingerprints",
               "An archive agent creates the dated archive, copies every artefact including the raw session transcript, and writes the report with a mandatory harness-enforcement stamp. If no artefact proves the gate fired, it must write “not found”, never infer it did.",
               [OP], leaves="The archive and its report"),
            st("F3", "The run audits itself", "Cannot end without a review, an explicit opt-out, or a documented failure",
               "The progress review scores the run and every reviewer lane, classifies each post-deploy bug as preventable or new, records gaps with an ID, a severity and a proposed rule, and checks that every red recommendation is shipped with evidence or retired with my words quoted. Four consecutive runs once skipped this step; the skip cost weeks of drift.",
               [O, S], leaves="The scorecard and the gap entries", block="No review artefact at all"),
        ]),
    ],
    metrics=[("34", "catalogued gates"), ("146", "hard-block instructions in the runbook"), ("8", "checkpoints that are mine")],
    fn=("Where the runbook's numbering is out of sequence the order follows its executable to-do list. Steps fire on their triggers: the data-flow trace on data lineage or migrations, the Solana gates on the two Solana codebases, the runtime test gate on fund-moving code, the external round when the run is flagged for it. "
        "Simple runs skip planning, the panel and the archive, but still run the deploy gate, a browser regression check and a tracker entry."),
)
