# Case study 2, rebuilt: the workflow from the inside. Facts: audit3/workflow_history_numbers.md, audit3/codex_workflow_story.md,
# audit3/workflow_breakdown.md (step detail), earlier facts docs. All counts as of 3 September 2026.
from content import DATE, GROWTH, GROWTH_FLAGS
SKILLS = "anchor-test-harness birdeye data-accuracy-check design-system-audit frontend-design helius helius-phantom integrating-jupiter meteora orca owasp-security postgres-patterns pumpfun raydium rust-skills safe-solana-builder solana-dev squads ui-ux-pro-max vulnhunter web-design-guidelines".split()

S2 = dict(
    slug="how-i-ship", num="02", title="How I ship", tab="How I ship",
    subtitle="The delivery workflow that ships SKYNET: AI models build every change, nothing ships until I approve it.",
    sections=[
    dict(id="cover", kind="cover",
         kicker="Case study 2 of 2 · how I ship",
         h1="AI models build every change. Nothing ships until I approve it.",
         lead=("One AI coordinates the job. Specialist agents research, plan, implement and test it. Models from two other vendors challenge the work before "
               "anything risky can ship. The whole thing runs on written rules that grew out of 112 documented runs, and every failure is kept."),
         metrics=[("112", "documented runs"), ("93", "of them declared complex"), ("4 days", "longest run, start to ship")],
         fn="Runs from 26 March to 1 September 2026, numbered 1 to 134 (22 numbers were skipped or abandoned). Complexity split 93 complex, 16 moderate, 1 simple, 2 unstated. Longest single session about 30 hours; longest calendar span 4 days (run 130). Measured " + DATE + ".",
         first="grew", other=("Case study 1 · The system", "the-system.html")),

    dict(id="grew", kind="growth",
         kicker="How it grew",
         h1="From a nine-line permissions file to an 11,009-line runbook",
         lead=("April 2025: one Python script pasted from a Grok chat. October 2025: the first AI-workflow file is a nine-line permissions list. "
               "26 November 2025: the delivery command is born at 284 lines, with an OpenAI reviewer written in from line one. "
               "Today the same file is 11,009 lines across 93 commits, and each addition is dated to the run that needed it."),
         milestones=[
            ("Oct 2025", "A nine-line permissions file. The whole AI workflow, on day one."),
            ("Nov 2025", "The delivery command, 284 lines. A second vendor's model reviews every plan from the first version."),
            ("Dec 2025", "The first gate scripts: file fingerprints and stale-archive detection. The file quadruples in five weeks."),
            ("Feb 2026", "Six specialist agents split the work: researcher, planner, implementer, two auditors, a validator."),
            ("Apr 2026", "The first testing harness and the progress review that scores every run."),
            ("May 2026", "The hardening quarter: +4,015 lines in one month, skills, handovers, and the workflow auditing itself for 28 hours."),
            ("Jul 2026", "A third vendor's model joins the panel, with routing that cuts review cost without touching money-critical work."),
            ("Sep 2026", "Run 134. Twenty-six agent roles, 22 skills, three harnesses, 34 gates."),
         ],
         note="The growth is rules added after failures, not features. Gates carry the run that needed them: “added 2026-07-03, Run 108”, “operator-caught 2026-08-18”."),

    dict(id="scope", kind="flow",
         kicker="Keeping AI in scope",
         h1="Three repositories, two servers, one map every agent must read first",
         lead=("The most important design choice is not the number of reviewers. It is the documentation system that tells each new AI where it is, "
               "what the surrounding system does, and which evidence controls the answer. Without it, agents spend their time blindly analysing 400,000 lines of code."),
         boxes=[
            ("Always loaded", "The constitution", "A rules file every agent reads on every turn. Its first rule: architecture before code, and the real code wins whenever the documentation disagrees."),
            ("2,110 lines", "The navigation index", "Maps every component to the section of the architecture map that explains it, generated from stable markers so an agent loads 200 lines, not 20,000."),
            ("19,514 lines", "The architecture map", "How the system works today: flows, tables, endpoints, contracts. No dates, no history, no debate. Rewritten after every change as if the feature had always existed."),
            ("3 contracts", "The canonical contracts", "Background jobs and tables, on-chain decoders, and tenant isolation each have one source of truth that must be updated in the same change as the code."),
            ("The code", "Source of truth", "Every plan, review and archive ends at the real files. A validator strips any line number or value that does not exist there."),
         ],
         points=[
            "An auditor starts at the navigation index, reads the one architecture section that matters, then the code. Three reads instead of a blind search across three repositories.",
            "After a run ships, the archive rewrites the affected architecture section and regenerates the navigation index. History goes into reports and archives; the map stays a map.",
            "A separate documentation audit has run 16 times since March 2026. It hunts undocumented code, obsolete statements, history creeping into the map, broken navigation and secrets, with a final adversarial pass over the documentation diff itself.",
         ],
         pane=["[d]CLAUDE.md · Rule Zero, verbatim[/d]",
               "[w]Your FIRST action on ANY code task MUST be reading the architecture. No exceptions. No \"quick grep first.\"[/w]",
               "  1. Read the navigation index and find the section for the component",
               "  2. Read the matching section of the architecture map",
               "  3. Read the actual source files and understand the existing flow",
               "  4. Then analyse or make changes",
               "[d]The actual source code is always the decisive factor. If the docs say one thing and the code does another, the code is correct.[/d]"],
         pane_cap="The rule every agent is bound by before it may touch code. Lightly shortened.",
         metrics=[("27,493", "lines of architecture documentation"), ("16", "documentation audits since March"), ("3", "canonical contracts, same-change updates")]),

    __import__("s2_run").RUN,

    dict(id="reviewers", kind="matrix",
         kicker="Who reviews",
         h1="Different vendors, different questions, and a record of who caught what",
         lead=("Lane count is not lane diversity. The panel mixes three model lineages, two blind roles and deterministic scripts, and every lane is scored, so the ledger shows which ones earn their place."),
         cols=["Lane", "Role", "Independence", "In the ledger"],
         rows=[
            ("Claude Opus", "#31d9ff", "Plans, implements, and reviews plan, code and architecture; maximum effort on complex runs", "Same lineage as the coordinator, different roles and contexts", "The most frequent lane; 16 plan rounds once blessed a feature flag that did not exist"),
            ("Claude Sonnet", "#31d9ff", "Coordinates, validates research and findings against the real code and data, cross-validates citations", "Fact-checker of everyone, including the coordinator", "Run 122: executed a test probe and overturned the coordinator's own refutation"),
            ("OpenAI Codex", "#a877ff", "Internal review lanes, a second data-flow trace, and the separately run external round", "Different vendor; the external round runs outside the workflow on a frozen commit", "Present in 111 of 112 runs; scored 9.33 of 10 across 51 scored runs; caught 15 critical findings in run 49 that Claude reviewers had approved"),
            ("xAI Grok", "#58e7ad", "Independent bug hunter on plan and code, added July 2026", "Third vendor; started non-blocking while it earned its place", "13 runs, 8.22 of 10 across 9 scored; run 128: contradicted a maximum-effort Claude critical, and the source proved Grok right"),
            ("Data-flow tracer", "#7d8ba3", "Compares the promised data path with the code, at plan time and again in the code", "Forbidden from reading the other reviewers' findings", "30 recorded passes, up to 35 of 35 assertions"),
            ("Scripts", "#7d8ba3", "Existence gates, schema checks, linters, brief redaction, prompt gate, routing", "Deterministic; no judgment, no fatigue", "144 hard-block markers; a gate stays red until it has executed on representative data"),
            ("Me", "#f2f6ff", "Scope, route, plan approval, release, verification sign-off, retirement of recommendations", "The only party that can authorise a deploy or retire a red finding", "Two of the six failures on this page were caught by me, not by any model"),
         ],
         points=[
            "A retired lane is retired in writing. The Google lane's own epitaph in the ledger: “1 unique finding in 13 runs”.",
            "External catches are counted per run. The field “external caught what internal missed” reads yes 78 times and no 14 times across the recorded rows, with a recorded streak of 40 consecutive runs.",
            "More reviewers did not always mean more truth. The latest run records four deployments and eleven review rounds in which nobody opened the page; the fix was a live round trip through the real screen, not another reviewer.",
         ],
         metrics=[("3", "model vendors on the panel"), ("2", "blind roles"), ("78 / 92", "recorded external catches, yes / total")],
         fn="Scores are the workflow's own progress reviews, kept in the run ledger. They are an internal quality record, not an independent certification."),

    dict(id="skills", kind="flow",
         kicker="Skills and harnesses",
         h1="Official references first, and proof they were used",
         lead=("Twenty-two skill packages, mostly official vendor documentation, are injected into every agent that needs them. Citing a skill is worth nothing on its own; a seven-checkpoint chain follows each one from plan to code to review."),
         boxes=[
            ("Checkpoint 1–2", "The planner cites", "The plan names the skills it used and the rules it applied. The plan auditor verifies each citation exists and says what the plan claims."),
            ("Checkpoint 3–4", "The implementer applies", "The implementation report maps each skill rule to a file and line in the diff. The coordinator checks the rule applied to this task at all."),
            ("Checkpoint 5–7", "The auditor proves", "The code auditor produces a compliance table, the harness patterns consulted are cited, and a review without them is rejected and re-run."),
         ],
         points=[
            "False or shallow use is named, not graded: a citation to a rule that does not exist is a broken citation; a skill mentioned but not applied is name-dropped; a required skill not used is a missing rejection.",
            "Three testing harnesses hold 4,763 lines of known failure patterns, one per past incident. A new safety gate stays red until it has run on representative data; reading the code does not count as executing it.",
            "Community snippets are treated as untrusted. One shipped the wrong byte offsets for a trading venue; official sources are now a hard gate, with pinned, digest-verified reference files.",
         ],
         pane=["[d].claude/skills/ · directory listing[/d]"] + ["  ".join(f"[k]{x}[/k]" if x in ("safe-solana-builder", "integrating-jupiter", "anchor-test-harness") else x for x in SKILLS[i:i+3]) for i in range(0, len(SKILLS), 3)] + ["[d]21 of 22 shown; one name is withheld because it names a product area not covered here[/d]"],
         pane_cap="The skill packages as they sit on disk. Several are official vendor documentation packaged for the models.",
         metrics=[("22", "skill packages"), ("7", "checkpoints per skill, per run"), ("4,763", "lines of harness patterns")]),

    dict(id="machinery", kind="flow",
         kicker="One machinery, five commands",
         h1="How a run survives the model losing its memory, and lasts for days",
         lead=("The durable unit is not the conversation. It is the run ID plus its evidence on disk. Five commands hand that state to each other, which is why a run can span two days, several sessions and two or three memory resets."),
         boxes=[
            ("audit-task", "The run", "The state machine described above: assess, research, plan, review, implement, review again, deploy, verify."),
            ("audit-task-handover", "The save file", "Before the model's memory is compacted, a timestamped handover records run identity, plan revision, phase, pending reviewers, the live to-do list and every owed gate."),
            ("resume", "Hypothesis, then proof", "A resumed model must restore the tracker, verify it against the live repository, re-arm every owed gate and re-read the architecture. The handover is a hypothesis; verification commands are the proof."),
            ("audit-archive", "The frozen record", "After deploy and testing: report, evidence package, file fingerprints, the rewritten architecture section, the regenerated index. Disposable artefacts are staged, never blindly deleted."),
            ("audit-task-progress", "The retrospective", "Scores the run and each reviewer lane. When no single transcript exists, it reconstructs the review from every handover, verdict and report, and sweeps all handovers for durable findings."),
            ("documentation-audit", "The periodic check", "Sixteen times so far: undocumented code, obsolete statements, history in the map, broken navigation, secrets, then an adversarial pass over the documentation diff."),
         ],
         points=[
            "Run 49 ran about 30 hours across two memory resets. Run 51, the workflow auditing itself, ran about 28 hours over two days across two resets and two handovers. Run 134 took three days and about 26 review passes.",
            "A run once dropped six findings that its first two handovers had deliberately recorded, because the review swept only the last handover. I caught it. The rule since: every handover in the chain is swept, and each carries machine-readable durable findings.",
            "678 handover files sit in the archives. Twelve are live on disk right now, belonging to two runs in flight.",
         ],
         metrics=[("30 h", "longest single session, run 49"), ("4 days", "longest calendar span, run 130"), ("678", "archived handover files")]),

    dict(id="failures", kind="beforeafter",
         kicker="Failures → controls",
         h1="Six times something broke, and what exists because of it",
         items=[
            ("The AI reported “done”. The file was unchanged.", "Every claimed edit is proven by the recorded changes before any reviewer sees it.", "Run 31", "Apr 2026"),
            ("An agent declared a test tool “not installed” after one shell lookup. It was installed.", "A standing rule: never assert a tool is missing from one lookup; the check looks in every valid install location.", "4 Jun", "2026"),
            ("A handover said the tests passed. The test record showed three failures, on transaction-critical code.", "Pass or fail is derived by a script from the test record, never from prose.", "Run 108", "Jul 2026"),
            ("Twelve external rounds said yes. The deploy locked the whole dashboard out for an hour: a refusal shipped before its data existed.", "A deploy-sequencing gate: populate before you enforce. Plans carry a release condition per feature.", "Run 127", "Aug 2026"),
            ("The safety test was green because its inputs were chosen where old and new code agree.", "Widened to 25 cases it went red: 28 production cases would have been handled wrongly. That corpus is now a gate.", "Run 132", "Aug 2026"),
            ("Eleven review rounds read the code; nobody opened the page. The feature would have refused every request.", "One live round trip through the real screen before reviewers are dispatched. Caught before release by the first test that did.", "Run 134", "Sep 2026"),
         ],
         note="From the run ledger, verbatim: “Every single one was found by widening the check, never by re-reading the same layer harder.”"),

    dict(id="scorecards", kind="scorecards",
         kicker="Scorecards",
         h1="Every run is graded, and so is every reviewer",
         card_caption="One real scorecard · run 133 · 19 Aug 2026 · from the written progress review",
         rows=[("Coordinator gates", 11, 12, "one recorded as not run, never as passed"), ("Reviewer checks", 10, 10, ""),
               ("Security, UI, verification", 8, 8, ""), ("Harness patterns cited", 14, 14, "plus 3 new patterns added"),
               ("Skill-use chain", 7, 7, "citations at every step"), ("OpenAI Codex lane", 10, 10, "no degraded rounds"),
               ("xAI Grok lane", 8, 10, "unique catch the other two missed; text output, not structured")],
         lineages=[("Claude Opus", "plans, implements, reviews architecture and code; maximum effort on complex runs"),
                   ("Claude Sonnet", "coordinates, validates plans and findings against the real code and data"),
                   ("OpenAI Codex", "internal review lanes and the separately run review; 9.33 of 10 across 51 scored runs"),
                   ("xAI Grok", "independent bug hunter, added July 2026; 8.22 of 10 across 9 scored runs"),
                   ("Data-flow tracer", "checks the promised data path at plan time and again in the code; 30 passes recorded, up to 35 of 35 assertions")],
         note=("The rubric has five tiers: 17 coordinator gates, 16 reviewer checks, 8 security and verification checks, 9 Solana gates, 6 harness-health rows. Each reviewer lane gets a plain-English grade, star to silent, and exactly one is named star performer. The best signal of a reviewer's value is its unique catches: findings nobody else found. A “no” is a gap by definition; every post-deploy bug is classified as preventable, partly preventable or new and mapped to the gate that should have caught it."),
         metrics=[("121", "written progress reviews"), ("5", "lineages graded per run"), ("30", "data-flow passes · up to 35/35")]),

    dict(id="gaps", kind="funnel",
         kicker="Gaps",
         h1="Not every gap becomes a rule. The ones that return, or are red, must.",
         lead=("A gap is anything that should have fired and did not. Each gets a stable ID, a severity and a proposed fix. Then a triage rule decides what happens next, and it forces a decision rather than a fix."),
         rows=[("235", "gap IDs recorded since March 2026", 100), ("87", "cited inside a step, gate, script or test", 37), ("36", "open today", 15)],
         points=[
            "Red “must fix” recommendations must be dispositioned before the run can end: shipped, with file evidence, or retired, with my own words quoted verbatim. The coordinator may not paraphrase or infer a retirement. Yellow and green stay advisory.",
            "The rule exists because of a measurement: of six red recommendations in July 2026, none had reached a workflow file, while all six harness notes from the same reviews had. The only difference was the word “must” versus “may”.",
            "When an external reviewer catches what every internal lane missed, the harness is updated immediately or the waiver cites the rule that already covers it. In the ledger's words: the tracker is the diary, not the checklist.",
            "For test patterns there is a universality table: a mechanism seen in two or more runs, or affecting two of the three codebases, or with a greppable signature, becomes a pattern; a one-off becomes a note. Severity escalates on repetition, a claimed fix is grepped for before it counts, and a rule is retired only after three clean runs.",
         ],
         pane=["[d]AUDIT_TASK_RUN_TRACKER.md · four gaps that became rules, shortened[/d]",
               "[k]G-29[/k]  [w]runs 55–56[/w]  Skills accountability silently degraded when the coordinator implemented inline → a freshness gate: implementer output must be newer than the plan, or a re-spawn, or per-skill file-and-line citations  [g]SHIPPED 2026-05-17[/g]",
               "[k]G-71[/k]  [w]run 70[/w]  The longest run had three handovers and no single transcript, so the review could not run → a transcript-substitute mode rebuilt from handovers, verdicts and reports  [g]SHIPPED same day[/g]",
               "[k]G-122f[/k]  [w]run 2 of a hardening series[/w]  The review swept only the last handover and dropped six recorded findings; I caught it → every handover in the chain is swept and carries machine-readable durable findings  [g]SHIPPED 2026-07-27 · exercised in 5 runs[/g]",
               "[k]G-115a[/k]  [w]run 115[/w]  A money-moving run was handed a vanilla external brief; the external model then repeated the identical shortcut → the handoff now cross-checks the run's own flags  [g]SHIPPED[/g]",
               "[k]G-60[/k]  [w]run 67[/w]  Pre-existing navigation drift hard-blocked an innocent run → proposed: block only drift this task introduced  [r]DESIGN PENDING[/r]"],
         pane_cap="Gap IDs are never reused or renumbered. A retired recommendation is a legitimate outcome; an absent decision is not.",
         metrics=[("235", "gap IDs recorded"), ("87", "written into a step, gate, script or test"), ("36", "open today")]),

    dict(id="gates", kind="gates",
         kicker="Where it stops",
         h1="A claim without evidence stops the run",
         gates=[("“I edited the file.”", "The recorded changes show nothing changed. The claim is false. Back to implementation."),
                ("“The plan uses this piece of data.”", "That data does not exist in the database. Blocked before a line is written."),
                ("Transaction-critical code, no record that the tests ran.", "No deploy. The test record must exist and match this run."),
                ("The external brief contains a server address.", "Hard block. The brief never leaves the machine."),
                ("Fewer than four of five reviewers finished.", "Deployment blocked. A thinner panel is not a panel."),
                ("The external verdict is not back yet.", "Wait. There is no timeout. The point of the gate is the independent opinion.")],
         pane=["[d].claude/commands/audit-task.md · four of the 34 gates, shortened[/d]",
               "[v]Step 8.6[/v]  Live-execution gate, stage A: detect write + datetime trigger files; dry-run first; [r]HARD BLOCK[/r] on dry-run failure  [d](Run 46)[/d]",
               "[v]Step 8.7[/v]  Schema validation gate: every <alias>.<column> in the SQL diff is checked against the live schema; [r]HARD BLOCK[/r] on missing columns  [d](Run 47)[/d]",
               "[v]Step 8.8[/v]  Static linter gate: lint every changed Python file; [r]HARD BLOCK[/r] on unused plan-named variables  [d](Run 47)[/d]",
               "[v]Step 9A.1.5[/v]  Prompt gate: fires before every external auditor handoff; [r]HARD BLOCKs[/r] on a dirty brief",
               "[d]…[/d]  [w]\"Zero insertions or deletions means the implementer's claim is false.\"[/w]"],
         pane_cap="From the runbook, lightly shortened. Each gate carries the run that needed it.",
         metrics=[("34", "catalogued gates"), ("144", "“hard block” markers in the runbook")],
         note="Each gate is traceable to the run that needed it."),

    dict(id="economics", kind="points",
         kicker="Economics and endurance",
         h1="Two subscriptions and a thirty-dollar plan run all of it",
         points=[
            "Claude runs on a single Max subscription: the coordinator, every specialist agent and every Claude review lane count against that one quota. OpenAI Codex runs on a ChatGPT plan; xAI Grok on a thirty-dollar monthly plan. Those are my bills, not figures from the repository.",
            "Review cost is routed, not capped. A lighter fork of the whole workflow saves 40 to 55 percent of Claude tokens on moderate work by dropping duplicate lanes, and it never drops the external round. Since July 2026 a deterministic policy picks the model and effort per lane by complexity. In the measured A/B, deep reviews used 84.8 percent fewer tokens and standard runs 57.5 percent fewer, with zero missed high or critical findings across three samples.",
            "Money-moving work never routes cheaper: it always runs the full high-effort fleet. And no monetary budget is enforced anywhere in the workflow; the only budgets in the routing code are wall-clock timeouts. Endurance comes from handovers and archives, not from spending more.",
         ],
         metrics=[("−84.8%", "tokens on deep reviews after routing"), ("−57.5%", "on standard runs"), ("0", "missed high or critical findings, 3 samples")],
         fn="Subscription costs are the operator's statement. Token savings are from the routing A/B recorded in the repository. A control run before routing consumed about 13.4 million tokens; the routing canary cost about 268 thousand."),

    dict(id="measured", kind="tiles",
         kicker="Measured · " + DATE,
         h1="Measured, with the populations printed",
         tiles=[
            ("112", "documented runs, numbered 1 to 134", "26 March to 1 September 2026, about one run every 1.4 days. 93 complex, 16 moderate, 1 simple."),
            ("235", "gap IDs recorded · 87 written into a step, gate, script or test", "36 open today. A gap leaves the open list only after three confirming runs."),
            ("121", "written progress reviews", "Each scores gates fired, reviewer checks, skills used, harness patterns cited."),
            ("201", "archives since December 2025", "188 with a written report. Plan, code changes, review decisions and file fingerprints frozen per run."),
            ("78 / 92", "recorded rows where the external review caught what internal reviews missed", "Peak streak recorded: 40 consecutive runs."),
            ("62 / 112", "runs claiming zero post-deploy bugs", "The others are documented too, including one severity-one incident and one shipped-with-reverts."),
         ],
         note=("Every figure is from the run ledger, the archives or git, and the ledger is written by the same system it evaluates. It is a high-resolution internal record, not an independent certification. "
               "Multiple AI reviewers are not an independent security audit; where money or security is at stake, the boundary is a human specialist.")),

    dict(id="close", kind="close",
         kicker="See it running",
         h1="The archive and the system are the evidence.",
         lead="In an interview I can walk through one archived change and one live product flow: the evidence, the release decision, the result, and the limits of this approach.",
         sessions=[("One archived change, end to end", "A real run from the archive: the request, the plan, the review decisions and fix rounds, the separate review's verdict, my release decision, and what production showed afterwards."),
                   ("One live product flow", "The system this loop built, running: a signal arriving, the engine executing, the record it leaves, and the numbers behind case study 1.")],
         team="In a team I would own: scope and acceptance criteria, the review gates, release decisions, and the retrospective loop. Engineers own the code; the workflow makes their review load smaller, not larger.",
         next=("Case study 1 · The system", "the-system.html")),
    ],
)
